### PR TITLE
added scaffolding for reading values from the GUI

### PR DESCRIPTION
**Pull request by damithc**
Added some scaffolding to read values from the GUI. e.g. the name of the selected person.

### CODE REVIEW

**Comment by damithc** [comment]
@m133225 do you think this kind of scaffolding is needed or we can do this stuff using testFx alone? 
I'll add the comments if we decide to keep this code.
@YijinL this PR touches the model too, but minimally.

**Comment by damithc** [comment]
@m133225 if no objections, go ahead and merge this. In the meantime, we can keep a lookout for a better alternative. But delay merging if you want to research for a better alternative first.

**Comment by m133225** [comment]
Actually, I think simply providing a unique id for GUI components should be sufficient. FxRobot can then find for `#id` node and cast it to the type required. Will look at other alternatives first.

**Comment by damithc** [comment]
Yes, it should be sufficient for many cases, but not all. For example, how can we find things like the focused item in the list, the number of items in the list, if an item is faded, etc.?

**Comment by damithc** [comment]
I see. Yes, that sounds workable. I'll give it a try.

**Comment by damithc** [comment]
closing. No longer applicable.

**Pull request closed without merging**
