### PR TITLE
UI: Use icon to show pending state in a person card. #346

### LINKED ISSUE #346: UI: Use icon to show pending state in a person card.
Currently, pending state of a person is reflected by a different background color. I'm thinking that we should replace this by having a row of mini icons below the person profile image. A pending state could have something like the icon below.
1edited

Any comments and suggestion before i go ahead and implement this?

### PR DESCRIPTION
**Pull request by yl-coder**
Fixes #346 

Counting down:
image

Syncing:
image

### CODE REVIEW

**Comment by HansNewbie** [comment]
Code wise is fine.

**Comment by yl-coder** [comment]
Ok. @damithc any comments on the UI?

**Comment by damithc** [comment]
UI Looks fine. May be use a different color text? we can remove the yellow highlight.

**Comment by yl-coder** [comment]
image

How about this?

**Comment by yl-coder** [comment]
image

I feel that the selected-focus-color doesn't seem to match with red so much.

**Comment by damithc** [comment]
Have a white background for text in concern?

**Comment by yl-coder** [comment]
image

**Comment by yl-coder** [comment]
Added the white background. Improved it by making corner curvy and adding shadow effect. Otherwise  just a plain white rectangle background may look abit odd imo.

**Comment by damithc** [comment]
Sure, we can try that.

**Pull request merged**
