### PR TITLE
Create a new release V1.3.0ea

### PR DESCRIPTION
**Pull request by m133225**
Making an official PR for easier reference.

### CODE REVIEW

**Comment by m133225** [comment]
Never mind, seems like merging through command line is more appropriate as it can avoid merge commit messages.

**Comment by damithc** [comment]
I think releases are supposed to happen on the `early-access` or `stable` branches. @HansNewbie confirm.

**Comment by m133225** [comment]
Yes, this was a PR to merge `master` to `early-access`. Also, after merging on `early-access` and creating the release, I just simply merged back to master so that the version is updated on master

**Comment by HansNewbie** [comment]
Yes. Releases should happen on the branches. Usually I don't merge back to
master, in which the version in master will be outdated. Dev is expected to
look at last commit message in updating the version (in my case).

Otherwise, either merge back to master or update the version before merging
branches (both are as complicated in terms of workflow).

**Pull request closed without merging**
